---
title: "cluster visualization"
format: html
warning: false
message: false
# html standalone
standalone: true
editor: 
  markdown: 
    wrap: 72
    
---

## libraries

load a few libraries

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(ggthemes)
library(sf)
library(ggspatial)
library(viridis)
library(raster)
library(stringr)

library(factoextra)

library(ggOceanMaps)
library(grafify)
library(data.table)
library(Rcpp)
```

load the bioregions (DEG)


```{r}
md <- brick(here::here("data", "mixdepth", "cmems_mod_arc_phy_anfc_6km_detided_P1D-m_mlotst_1998.nc"))
```

bioregions

```{r}
#  
bio <- st_read(here::here('out', '1.1.0_cluster_8_gap_DEG.shp'))

r <- rasterize(bio, md, field = "cluster")
names(r) <- "cluster"





```

output data frame


```{r} 
st <- stack(r, md)

stdf <- as.data.frame(st, xy = TRUE) |> filter(!is.na(cluster))

stlong <- pivot_longer(stdf, c(4:ncol(stdf)), names_to = "variable", values_to = "value") |>
	# use lubridate to extract date from variable (remobing the "X" at the beginning)
	mutate(date = lubridate::ymd(substr(variable, 2, 11))) 

stlong$bioregions <- factor(stlong$cluster, levels = c(0: 7, -1), labels = c("1", "2", "3", "4", "5", "6", "7", "8", "other"))

out <- stlong

```


```{r}

for(year in 1999:2022){
	
	md <- 	brick(here::here("data", "mixdepth",
							paste0("cmems_mod_arc_phy_anfc_6km_detided_P1D-m_mlotst_", 
										 year, ".nc")))
	st <- stack(r, md)
	stdf <- as.data.frame(st, xy = TRUE) |> filter(!is.na(cluster))
	
	stlong <- pivot_longer(stdf, c(4:ncol(stdf)), names_to = "variable", values_to = "value") |> 	mutate(date = lubridate::ymd(substr(variable, 2, 11))) 
	
	stlong$bioregions <- factor(stlong$cluster, levels = c(0: 7, -1), labels = c("1", "2", "3", "4", "5", "6", "7", "8", "other"))
	
	out <- rbind(out, stlong)
	
	
	print(year)
	
}

saveRDS(out, here::here("data", "1.2.3_bioregions_mixeddepth.rds"))



```

summary statistics



```{r}
su <- out |> 
	mutate(year = lubridate::year(date)) |>
	group_by(bioregions, cluster, year) |>
	summarise(meanmlotst  = mean(value, na.rm = TRUE), sdmlotst  = sd(value, na.rm = TRUE), n = n(),
		q10mlotst = quantile(value, probs = 0.1, na.rm = TRUE),
		q90mlotst = quantile(value, probs = 0.9, na.rm = TRUE))

write.csv(su, here::here("data", "1.2.3_bioregions_mixeddepth_summary.csv"))
saveRDS(su, here::here("data", "1.2.3_bioregions_mixeddepth_summary.rds"))



```


```{r}
out <-readRDS(here::here("data", "1.2.3_bioregions_mixeddepth.rds"))

```

```{r}
ggplot(su, aes(year, meanmlotst, colour = bioregions)) +
	geom_line() +
	geom_point() +

	theme_few() +
	theme(legend.position = "none") +

	scale_colour_grafify(palette = "kelly") +
	labs(x = "year", y = "mean mixed layer depth (m)") +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	facet_wrap(~bioregions, ncol = 3, scale = "free_y") 

ggsave(here::here("out", "1.2.3_bioregions_mixeddepth_mean.png"), width = 12, height = 8, dpi = 300)



```




```{r}

# select 1998, 2008, 2018
outplot <- out |> 
	mutate(year = lubridate::year(date)) |>
	filter(year %in% c(1998, 2008, 2018)) |> 
	group_by(bioregions,  year) |>
	# sample 3000 points
	sample_n(5000) 
	
	


ggplot(outplot |> filter(!is.na(bioregions)), aes(bioregions, value, fill = bioregions, colour = bioregions)) +

	facet_wrap(~year, ncol = 3)+ 
  ## add half-violin from {ggdist} package
  ggdist::stat_halfeye(
    ## custom bandwidth
    adjust = .5, 
    ## adjust height
    width = .6, 
    ## move geom to the right
    justification = -.2, 
    ## remove slab interval
    .width = 0, 
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .15, 
    ## remove outliers
    outlier.color = NA,
    colour = "grey20",
    fill = NA## `outlier.shape = NA` or `outlier.alpha = 0` works as well
  ) +
  ## add dot plots from {ggdist} package
  ggdist::stat_dots(
    ## orientation to the left
    side = "left", 
    ## move geom to the left
    justification = 1.12, 
    ## adjust grouping (binning) of observations 
    binwidth = .25,
    size = 1.1,
    alpha = 0.3
  ) +
	theme_few() +
		theme(legend.position = "none") +
	#scale_fill_grafify()+
	 grafify::scale_fill_grafify(palette = "kelly") +
	grafify::scale_colour_grafify(palette = "kelly") +
	xlab("Bioregion") +
	ylab("Mixed layer depth (m)")

ggsave(here::here("out", paste0("1.2.3_bioregion_mixedlayer.png")), width = 16, height = 8, dpi = 300, bg = "white")


```

```{r}
```

